### ISSUE TITLE
Runtime notes template contains stale roadmap

### ISSUE THREAD

**Issue by amitkgupta** [cloudfoundry/pmc-notes#62]
Hey,

The Runtime notes template has a [roadmap at the bottom](https://github.com/cloudfoundry/pmc-notes/blob/master/Runtime/2018/2018-07-24-runtime.md#cf-feature-roadmap-review).  I was a bit confused by what I saw there in the most recent notes, until I realized it was copy-pasted for every note.  It looks like it doesn't get updated with every PMC meeting, but then it ends up with misleading info.  Would it be better to have a blank roadmap in the template... or perhaps have something different like a public Trello for roadmap that might be easier to update than the markdown?

/cc @emalm @julz @dieucao 

Cheers,
Amit

**Comment by emalm** [comment]
I'm in favor of simply deleting that section in the notes for the time being, as I'm not aware of anyone asking for it to be up to date and the Runtime PMC project leads collectively haven't found it valuable enough to maintain.

**Comment by amitkgupta** [comment]
Yeah, I think it's best if the info there isn't confusing, could be solved by deleting it or keeping it up to date.  I'm not sure whether the community finds this roadmap a valuable way to have a sense for what's going on/coming up vs. other means of learning the same things...

**Comment by youngm** [comment]
I look at the roadmap and find it somewhere useful.

**Comment by emalm** [comment]
Thanks, @amitkgupta and @youngm. I'll raise the topic of maintaining a more cohesive roadmap to the Runtime PMC [soon](https://github.com/cloudfoundry/pmc-notes/blob/master/Runtime/2018/2018-09-04-runtime.md#discussion). In the meantime, since that section was mostly out of date, I've deleted it. I'd also like to make sure that each of the Runtime project leads provides at least monthly updates in the meeting notes, if not biweekly.
